// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yidujufgbevuzwzodjln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZHVqdWZnYmV2dXp3em9kamxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTg0NjcsImV4cCI6MjA3MjY3NDQ2N30.HtjdsAaZb5wNMW8XyTn-oWoNtqw0kFRub-fUnl-ZejM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});